#!/usr/bin/env python3
"""
Script: generate_posts.py
Description: Reads raw news from data/raw_news.json and uses local AI models
             (running via Ollama on the GitHub Actions runner) to generate editorial
             posts and reactions from the panel bots defined in data/personas.json.
"""

import os
import json
import time
import re
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional
import requests

# Directories and file paths
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "data")
RAW_NEWS_FILE = os.path.join(DATA_DIR, "raw_news.json")
PERSONAS_FILE = os.path.join(DATA_DIR, "personas.json")
POSTS_FILE = os.path.join(DATA_DIR, "posts.json")

# Ollama settings (running locally on the Actions runner)
OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://localhost:11434")
OLLAMA_MODEL = os.getenv("OLLAMA_MODEL", "batiai/gemma4-e4b:q4")
REQUEST_TIMEOUT = int(os.getenv("OLLAMA_TIMEOUT", "120"))


def call_ollama(prompt: str, system_prompt: str = "", temperature: float = 0.4) -> str:
    """
    Sends a request to the local Ollama API on the runner, forcing JSON response.
    Default temperature set to 0.4 (focus and coherence).
    """
    url = f"{OLLAMA_HOST}/api/generate"
    payload = {
        "model": OLLAMA_MODEL,
        "prompt": prompt,
        "system": system_prompt,
        "stream": False,
        "format": "json",  # forces native JSON in the Ollama API
        "options": {
            "temperature": temperature,
            "top_p": 0.9,
        }
    }

    try:
        response = requests.post(url, json=payload, timeout=REQUEST_TIMEOUT)
        response.raise_for_status()
        data = response.json()
        return data.get("response", "").strip()
    except Exception as e:
        print(f"  [ERROR Ollama] Failed to query the model ({OLLAMA_MODEL}): {e}")
        return ""


def clean_response_text(text: str) -> str:
    """
    Removes outer quotes or unnecessary markdown tags generated by LLMs.
    """
    clean = text.strip()
    if (clean.startswith('"') and clean.endswith('"')) or (clean.startswith("'") and clean.endswith("'")):
        clean = clean[1:-1].strip()
    return clean


# Base system prompt for the editorial persona — sharp, direct, no clichés
_EDITOR_SYSTEM_PROMPT = """You are a sharp, direct, and incisive technology journalist and analyst.
Absolute rules:
- NEVER use generic opening phrases like "Here is the post", "Sure!", "With pleasure".
- NEVER use clichés like "In today's globalized world", "Technology advances by leaps and bounds".
- Get straight to the point. Tone: critical, informative, mildly ironic when appropriate.
- ALWAYS respond in English.
- Respond ONLY with the requested JSON, no additional text, no markdown blocks."""


def _parse_json_safe(text: str) -> Optional[Dict[str, Any]]:
    """
    Tries to extract and parse JSON from the string returned by Ollama.
    Removes possible markdown fences (```json ... ```) before parsing.
    """
    # Remove markdown fences if present
    cleaned = re.sub(r"```(?:json)?\s*", "", text).strip()
    # Try to parse directly
    try:
        return json.loads(cleaned)
    except json.JSONDecodeError:
        pass
    # Try to find the first valid JSON object in the string
    match = re.search(r"\{.*\}", cleaned, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(0))
        except json.JSONDecodeError:
            pass
    return None


def generate_post_content(news_item: Dict[str, Any], editor_persona: Dict[str, Any]) -> Dict[str, Any]:
    """
    Generates the full post in the standardized schema using the sharp editorial persona.
    Returns a dict with keys: titulo, resumo_executivo, conteudo_post, reacao_emoji, tags.
    """
    # Use the persona's system_prompt if defined, otherwise use the default editorial one
    system_prompt = editor_persona.get("system_prompt") or _EDITOR_SYSTEM_PROMPT
    temperature = max(0.3, min(0.5, editor_persona.get("temperature", 0.4)))

    prompt = f"""Raw news item for analysis:
Original Title: {news_item.get('titulo')}
Source: {news_item.get('fonte')}
Original Summary: {news_item.get('resumo_original')}

Generate a technology post in English following EXACTLY this JSON schema:
{{
  "titulo": "Impactful title (max 80 characters)",
  "resumo_executivo": "One direct sentence summarizing what happened (max 150 characters)",
  "conteudo_post": "Critical and informative analysis in 2-3 paragraphs (max 800 characters total)",
  "reacao_emoji": "A single emoji representing the AI's reaction to the news",
  "tags": ["RelevantTag1", "RelevantTag2", "RelevantTag3"]
}}"""

    response_text = call_ollama(prompt, system_prompt=system_prompt, temperature=temperature)
    parsed = _parse_json_safe(response_text)

    if parsed is None:
        print(f"  [WARNING] Ollama response contains no valid JSON. Using fallback.")
        return {
            "titulo": news_item.get("titulo", "Untitled News"),
            "resumo_executivo": news_item.get("resumo_original", "")[:150],
            "conteudo_post": news_item.get("resumo_original", "Content not available."),
            "reacao_emoji": "📰",
            "tags": ["Technology"],
        }

    # Sanitize text fields
    for key in ("titulo", "resumo_executivo", "conteudo_post", "reacao_emoji"):
        if key in parsed and isinstance(parsed[key], str):
            parsed[key] = clean_response_text(parsed[key])

    # Ensure tags is always a list of non-empty strings
    if not isinstance(parsed.get("tags"), list):
        parsed["tags"] = ["Technology"]
    else:
        parsed["tags"] = [str(t).strip() for t in parsed["tags"] if str(t).strip()]

    return parsed


def generate_bot_reaction(
    news_title: str,
    news_summary: str,
    bot_id: str,
    persona: Dict[str, Any]
) -> str:
    """
    Generates an in-depth analytical commentary from a specific bot for the news item.
    Temperature kept at 0.4 for voice coherence per persona.
    """
    system_prompt = persona.get("system_prompt", "")
    temperature = max(0.3, min(0.5, persona.get("temperature", 0.4)))

    prompt = f"""News headline: {news_title}
Factual context: {news_summary}

Rules:
- Fully embody the personality of {persona.get('nome')}.
- Write a 3-5 sentence analytical commentary (400-700 characters) examining this news from your unique perspective.
- Go beyond surface-level reaction: analyze implications, question assumptions, or highlight what others might miss.
- Do NOT invent facts that are not present in the factual context above.
- NO introductions like "Sure!" or "Here is my take".
- ALWAYS respond in English.
- Respond ONLY with the commentary text in JSON: {{"reacao": "text here"}}"""

    raw = call_ollama(prompt, system_prompt=system_prompt, temperature=temperature)
    parsed = _parse_json_safe(raw)
    if parsed and isinstance(parsed.get("reacao"), str):
        reaction = clean_response_text(parsed["reacao"])
    else:
        # Fallback: try using the raw string if the model didn't respect JSON
        reaction = clean_response_text(raw)

    if not reaction:
        fallbacks = {
            "cynic": (
                "Another day, another round of breathless announcements designed to distract from the fact "
                "that nothing fundamentally changes. The real winners here are the cloud providers and the "
                "PR agencies, while the rest of us are left deciphering yet another press release dressed "
                "up as innovation. When the dust settles, ask yourself: who actually profits from this, "
                "and who was already doing just fine without it?"
            ),
            "optimist": (
                "This is exactly the kind of development that reminds us why the pace of technological "
                "progress is so extraordinary. The potential here extends far beyond what's immediately "
                "visible — think about the downstream effects on accessibility, collaboration, and the "
                "democratization of tools that were once reserved for well-funded organizations. "
                "The future isn't just arriving; it's accelerating, and this is a meaningful step forward."
            ),
            "skeptic": (
                "Before we declare victory, let's talk about what the announcement conspicuously leaves out: "
                "failure modes, security surface area, operational overhead at scale, and the inevitable "
                "edge cases that will surface in production. Controlled demos are one thing; real-world "
                "deployments with unpredictable traffic, adversarial inputs, and legacy integration "
                "requirements are another beast entirely. Show me the post-mortem from six months in."
            ),
            "humorous": (
                "Ah yes, the classic tech cycle: announce, hype, deploy, discover the bug that only "
                "manifests on a Tuesday at 3am in a specific timezone, patch it in a hotfix with "
                "a suspiciously vague changelog entry. I'm already drafting the incident report in my head. "
                "But hey, at least the loading spinner will be 12% more responsive — and honestly, "
                "that's the innovation we deserve."
            ),
        }
        reaction = fallbacks.get(bot_id, "Commentary is being processed.")

    return reaction


def main():
    print("=" * 60)
    print(f"Starting AI post generation (Ollama: {OLLAMA_MODEL})")
    print(f"Timestamp: {datetime.now(timezone.utc).isoformat()}")
    print("=" * 60)

    # 1. Load personas
    if not os.path.exists(PERSONAS_FILE):
        print(f"[ERROR] Personas file not found: {PERSONAS_FILE}")
        return

    with open(PERSONAS_FILE, "r", encoding="utf-8") as f:
        personas = json.load(f)

    # 2. Load raw news
    if not os.path.exists(RAW_NEWS_FILE):
        print(f"[INFO] No {RAW_NEWS_FILE} found. Exiting.")
        return

    with open(RAW_NEWS_FILE, "r", encoding="utf-8") as f:
        raw_news = json.load(f)

    if not raw_news:
        print("[INFO] No new news in raw_news.json to process.")
        return

    print(f"[INFO] {len(raw_news)} news item(s) found for processing.")

    # 3. Load existing posts to keep history and avoid duplication
    existing_posts = []
    existing_ids = set()
    if os.path.exists(POSTS_FILE):
        try:
            with open(POSTS_FILE, "r", encoding="utf-8") as f:
                existing_posts = json.load(f)
                if isinstance(existing_posts, list):
                    existing_ids = {p.get("id") for p in existing_posts if "id" in p}
        except Exception as e:
            print(f"[WARNING] Error loading {POSTS_FILE}: {e}")

    editor_persona = personas.get("editor", {})
    reaction_bot_ids = [b_id for b_id in personas.keys() if b_id != "editor"]

    new_posts: List[Dict[str, Any]] = []

    for index, item in enumerate(raw_news, start=1):
        item_id = item.get("id")
        if item_id in existing_ids:
            print(f"[{index}/{len(raw_news)}] Skipping already-existing item in posts.json (ID: {item_id})")
            continue

        print(f"\n[{index}/{len(raw_news)}] Processing: {item.get('titulo')[:50]}...")

        # a) Generate post in the standardized schema
        print("  -> Generating editorial post (Nexus Editor)...")
        post_data = generate_post_content(item, editor_persona)
        # Use conteudo_post as context base for bot reactions
        summary_for_bots = post_data.get("resumo_executivo") or post_data.get("conteudo_post", "")[:300]

        # b) Generate bot panel reactions
        replies = []
        for bot_id in reaction_bot_ids:
            persona = personas.get(bot_id, {})
            bot_name = persona.get("nome", bot_id)
            print(f"  -> Generating reaction from {bot_name} ({bot_id})...")

            reaction_text = generate_bot_reaction(
                news_title=post_data.get("titulo", item.get("titulo", "")),
                news_summary=summary_for_bots,
                bot_id=bot_id,
                persona=persona,
            )

            replies.append({
                "id": f"rep-{item_id}-{bot_id}",
                "botId": bot_id,
                "text": reaction_text,
            })

        # Build the NewsPost object with the new schema + frontend compatibility fields
        post_obj = {
            "id": item_id,
            # New standardized schema fields
            "titulo": post_data.get("titulo", item.get("titulo", "News")),
            "resumo_executivo": post_data.get("resumo_executivo", ""),
            "conteudo_post": post_data.get("conteudo_post", ""),
            "reacao_emoji": post_data.get("reacao_emoji", "📰"),
            "tags": post_data.get("tags", []),
            # Frontend React compatibility fields
            "title": post_data.get("titulo", item.get("titulo", "News")),
            "category": ", ".join(post_data.get("tags", ["Technology"])[:1]),
            "publishedAt": item.get("data_publicacao", datetime.now(timezone.utc).isoformat()),
            "paragraphs": [p for p in post_data.get("conteudo_post", "").split("\n") if p.strip()],
            "sourceName": item.get("fonte", "External Source"),
            "sourceUrl": item.get("link", "#"),
            "replies": replies,
        }

        new_posts.append(post_obj)

    # 4. Save output
    if new_posts:
        # New posts on top, preserving history
        consolidated_posts = new_posts + existing_posts

        # Reasonable limit to keep the feed from growing indefinitely (e.g. last 50 news items)
        consolidated_posts = consolidated_posts[:50]

        os.makedirs(DATA_DIR, exist_ok=True)
        with open(POSTS_FILE, "w", encoding="utf-8") as f:
            json.dump(consolidated_posts, f, indent=2, ensure_ascii=False)

        print("\n" + "=" * 60)
        print(f"[SUCCESS] {len(new_posts)} new post(s) generated and saved to {POSTS_FILE}.")
        print(f"Total accumulated in posts.json: {len(consolidated_posts)}")
        print("=" * 60)
    else:
        print("\n[INFO] No new posts needed to be generated.")


if __name__ == "__main__":
    main()
