import { BotInfo, BotPersonality, NewsPost, WeeklyEdition } from '../types';
import postsJson from '../../data/posts.json';
import personasJson from '../../data/personas.json';

interface RawPersona {
  id?: string;
  nome: string;
  tag_personalidade: string;
  toneType: string;
  avatar_seed?: string;
  accent_color?: string;
  descricao: string;
  system_prompt?: string;
  temperature?: number;
}

const personalityDisplayLabels: Record<string, string> = {
  editor: 'Factual Editor',
  factual: 'Factual Editor',
  cynic: 'Cynic',
  // PT aliases kept so existing posts.json data still resolves
  cínico: 'Cynic',
  optimist: 'Optimist',
  otimista: 'Optimist',
  skeptic: 'Skeptic',
  cético: 'Skeptic',
  humorous: 'Humor & Satire',
  engraçado: 'Humor & Satire'
};

// Process personas into standard BotInfo objects
const rawPersonas = personasJson as Record<string, RawPersona>;

export const BOTS: Record<string, BotInfo> = Object.entries(rawPersonas).reduce(
  (acc, [key, p]) => {
    const rawTag = (p.tag_personalidade || key).toLowerCase();
    const shortDesc = p.descricao ? p.descricao.split('.')[0] + '.' : '';

    acc[key] = {
      id: p.id || key,
      name: p.nome || key,
      personality: personalityDisplayLabels[rawTag] || p.tag_personalidade || p.nome,
      toneType: (p.toneType as BotPersonality) || 'neutral',
      avatarSeed: p.avatar_seed || p.nome || key,
      accentColor: p.accent_color || '#f59e0b',
      description: p.descricao || '',
      shortBio: shortDesc
    };
    return acc;
  },
  {} as Record<string, BotInfo>
);

// Fallback editor if not defined in personas.json
if (!BOTS.editor) {
  BOTS.editor = {
    id: 'editor',
    name: 'Nexus Editor',
    personality: 'Factual Editor',
    toneType: 'neutral',
    avatarSeed: 'NexusEditorBot',
    accentColor: '#f59e0b',
    shortBio: 'Synthesizes raw facts based on primary sources.',
    description: 'Editor-in-chief responsible for strictly factual curation and synthesis of news.'
  };
}

// Real news posts loaded from data/posts.json
export const NEWS_ARTICLES: NewsPost[] = (postsJson as NewsPost[]) || [];

// Helper to format ISO date strings into readable en-US dates
export function formatNewsDate(dateStr: string): string {
  if (!dateStr) return '';
  try {
    const d = new Date(dateStr);
    if (isNaN(d.getTime())) return dateStr;
    return new Intl.DateTimeFormat('en-US', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    }).format(d);
  } catch {
    return dateStr;
  }
}

// Helper to build a dynamic Weekly Edition based on real articles in posts.json
export function getWeeklyEdition(): WeeklyEdition | null {
  if (!NEWS_ARTICLES || NEWS_ARTICLES.length === 0) {
    return null;
  }

  // Find featured debate from real posts
  let debatePost = NEWS_ARTICLES.find(
    (p) => p.replies && p.replies.length >= 2 && p.replies.some((r) => r.botId === 'cynic') && p.replies.some((r) => r.botId === 'optimist')
  );

  if (!debatePost && NEWS_ARTICLES.length > 0) {
    debatePost = NEWS_ARTICLES[0];
  }

  const cynicReply = debatePost?.replies?.find((r) => r.botId === 'cynic') || debatePost?.replies?.[0];
  const optimistReply = debatePost?.replies?.find((r) => r.botId === 'optimist') || debatePost?.replies?.[1];

  // Derive date range from articles
  const firstDate = NEWS_ARTICLES[NEWS_ARTICLES.length - 1]?.publishedAt;
  const lastDate = NEWS_ARTICLES[0]?.publishedAt;
  const dateRangeStr = `${formatNewsDate(firstDate)} — ${formatNewsDate(lastDate)}`;

  // Summary sections from real posts
  const topArticles = NEWS_ARTICLES.slice(0, 3);
  const sections = topArticles.map((article) => ({
    title: article.title,
    content: article.paragraphs.slice(0, 2),
    pullQuote: article.paragraphs[0]
  }));

  return {
    editionNumber: 1,
    dateRange: dateRangeStr,
    title: 'Overview of the Latest Technology Developments',
    subtitle: `A compilation of ${NEWS_ARTICLES.length} verified news items commented on by the automated editorial panel.`,
    sections,
    highlightDebate: {
      title: `Featured Debate: "${debatePost?.title || 'Tech Discussion'}"`,
      bot1: {
        botId: cynicReply?.botId || 'cynic',
        quote: cynicReply?.text || 'Awaiting comments from the editorial panel.'
      },
      bot2: {
        botId: optimistReply?.botId || 'optimist',
        quote: optimistReply?.text || 'Awaiting comments from the editorial panel.'
      }
    },
    conclusion: 'Stay tuned for continuous updates generated by the automated ingestion and AI analysis workflows.'
  };
}
